### ISSUE TITLE
Enhancement - bash script to build docker containers

### ISSUE THREAD

**Issue by johndpope** [choefele/swift-server-app#3]
I built this file to bring up multiple docker containers.
Maybe of some use to someone
https://gist.github.com/johndpope/393f0735b6555005c234088422f0414d

**Comment by johndpope** [comment]
@choefele - thanks for your efforts here. 
am looking to doing some grpc in swift with tensorflow some day.

here's a hack with inception model I worked on the other week 
https://github.com/nubbel/swift-tensorflow/

**Comment by choefele** [comment]
Thanks for your script and your Swift project. Good to have examples on how to do this
